# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.


In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3, 4, 5])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3], [3, 4, 5]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[3, 4, 2], [9, 8, 4]]])
a3


array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 4, 2],
        [9, 8, 4]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.


In [3]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, type(a1), a1.size


((5,), 1, dtype('int64'), numpy.ndarray, 5)

In [4]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, type(a2), a2.size


((2, 3), 2, dtype('int64'), numpy.ndarray, 6)

In [5]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, type(a3), a3.size


((2, 2, 3), 3, dtype('int64'), numpy.ndarray, 12)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df


0  1  2
0  1  2  3
1  3  4  5

In [7]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
range = np.arange(0, 100, 3)
range


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_numbers = np.random.randint(0, 10, (7, 2))
random_numbers


array([[0, 4],
       [0, 8],
       [5, 8],
       [7, 1],
       [4, 9],
       [4, 5],
       [5, 5]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_floats = np.random.rand(3, 5)
random_floats


array([[0.03043214, 0.95574422, 0.02223851, 0.06477438, 0.21191648],
       [0.60783615, 0.17637151, 0.15356466, 0.36599469, 0.51168068],
       [0.3809277 , 0.99275576, 0.93336544, 0.34888085, 0.15741114]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array = np.random.randint(0, 10, (4, 6))
random_array


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?


In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np.random.seed(0)
random_array2 = np.random.randint(1, 10, (3, 7))
random_array2

# Find the unique numbers in the array you just created
# np.unique(random_array2)


array([[6, 1, 4, 4, 8, 4, 6],
       [3, 5, 8, 7, 9, 9, 2],
       [7, 8, 8, 9, 2, 6, 9]])

In [14]:
# Find the 0'th index of the latest array you created
random_array2[:1, :1]


array([[6]])

In [15]:
# Get the first 2 rows of latest array you created
random_array2[:2]


array([[6, 1, 4, 4, 8, 4, 6],
       [3, 5, 8, 7, 9, 9, 2]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
random_array2[:2, :2]


array([[6, 1],
       [3, 5]])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array3 = np.random.randint(0, 10, (3, 5))
ones = np.ones((3, 5))
ones


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
# Add the two arrays together
sum = random_array3+ones
sum


array([[10.,  5.,  4.,  1.,  4.],
       [ 6.,  1.,  3.,  4.,  9.],
       [ 2.,  4.,  4.,  4.,  8.]])

In [19]:
# Create another array of ones of shape (5, 3)
ones2 = np.ones((5, 3))
ones2


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# Try add the array of ones and the other most recent array together
random_array3+ones2.T


array([[10.,  5.,  4.,  1.,  4.],
       [ 6.,  1.,  3.,  4.,  9.],
       [ 2.,  4.,  4.,  4.,  8.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?


In [21]:
# Create another array of ones of shape (3, 5)
ones3 = np.ones((3, 5))
ones


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Subtract the new array of ones from the other most recent array
subtract = np.subtract(random_array3, ones3)
subtract


array([[ 8.,  3.,  2., -1.,  2.],
       [ 4., -1.,  1.,  2.,  7.],
       [ 0.,  2.,  2.,  2.,  6.]])

In [23]:
# Multiply the ones array with the latest array
multiply = np.multiply(random_array3, ones3)
multiply


array([[9., 4., 3., 0., 3.],
       [5., 0., 2., 3., 8.],
       [1., 3., 3., 3., 7.]])

In [24]:
# Take the latest array to the power of 2 using '**'
random_array3**2


array([[81, 16,  9,  0,  9],
       [25,  0,  4,  9, 64],
       [ 1,  9,  9,  9, 49]])

In [25]:
# Do the same thing with np.square()
np.square([random_array3, 2])


/tmp/ipykernel_44236/296470134.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.square([random_array3, 2])


array([array([[81, 16,  9,  0,  9],
              [25,  0,  4,  9, 64],
              [ 1,  9,  9,  9, 49]]), 4], dtype=object)

In [26]:
# Find the mean of the latest array using np.mean()
np.mean(random_array3)


3.6

In [27]:
# Find the maximum of the latest array using np.max()
np.max(random_array3)


9

In [28]:
# Find the minimum of the latest array using np.min()
np.min(random_array3)


0

In [29]:
# Find the standard deviation of the latest array
np.std(random_array3)


2.5768197453450252

In [30]:
# Find the variance of the latest array
np.var(random_array3)


6.640000000000001

In [31]:
# Reshape the latest array to (3, 5, 1)
np.reshape(random_array3, (3, 5, 1))


array([[[9],
        [4],
        [3],
        [0],
        [3]],

       [[5],
        [0],
        [2],
        [3],
        [8]],

       [[1],
        [3],
        [3],
        [3],
        [7]]])

In [32]:
# Transpose the latest array
random_array3.T


array([[9, 5, 1],
       [4, 0, 3],
       [3, 2, 3],
       [0, 3, 3],
       [3, 8, 7]])

What does the transpose do?


In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array4 = np.random.randint(0, 10, (3, 2))
random_array5 = np.random.randint(0, 10, (3, 3))
random_array5


array([[7, 3, 2],
       [7, 2, 0],
       [0, 4, 5]])

In [34]:
# Perform a dot product on the two newest arrays you created
# np.dot(random_array4.T,random_array5)
np.dot(random_array5, random_array4)


array([[27, 42],
       [18, 25],
       [36, 56]])

In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array6 = np.random.randint(0, 10, (4, 3))
random_array7 = np.random.randint(0, 10, (4, 3))
random_array7


array([[9, 3, 6],
       [7, 2, 0],
       [3, 5, 9],
       [4, 4, 6]])

In [36]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array4.T, random_array6.T)


array([[ 54,   9,  72,  63],
       [ 91,  29,  85, 100]])

It doesn't work. How would you fix it?


In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.shape(random_array5), np.shape(random_array7)
np.dot(random_array5, random_array7.T)


array([[84, 55, 54, 52],
       [69, 53, 31, 36],
       [42,  8, 65, 46]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.


In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
np.random.seed(23)
arr1 = np.random.randint(0, 10, (3, 4))
arr2 = np.random.randint(0, 10, (3, 4))
arr2


array([[5, 5, 0, 5],
       [0, 9, 9, 3],
       [1, 7, 4, 1]])

In [39]:
# Compare the two arrays with '>'
arr1 > arr2


array([[False,  True,  True,  True],
       [ True, False, False,  True],
       [ True, False, False,  True]])

What happens when you compare the arrays with `>`?


In [40]:
# Compare the two arrays with '>='
arr1 >= arr2


array([[False,  True,  True,  True],
       [ True, False, False,  True],
       [ True, False, False,  True]])

In [41]:
# Find which elements of the first array are greater than 7
arr1 > 7


array([[False, False,  True,  True],
       [False,  True, False,  True],
       [False, False, False, False]])

In [42]:
# Which parts of each array are equal? (try using '==')
arr1 == arr2


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [43]:
# Sort one of the arrays you just created in ascending order
np.sort(arr1)


array([[3, 6, 8, 9],
       [6, 7, 8, 9],
       [1, 2, 3, 6]])

In [44]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr1)


array([[0, 1, 2, 3],
       [0, 2, 1, 3],
       [2, 3, 0, 1]])

In [45]:
arr1


array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [46]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr1)


3

In [47]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr1)


10

In [48]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr1, axis=1)


array([3, 3, 1])

In [49]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr1, axis=0)


array([0, 0, 2, 2])

In [50]:
# Create an array of normally distributed random numbers
np.random.normal(0, 1, 10)


array([-2.41201527, -0.45175246,  1.17420672,  0.76634838, -0.36181507,
        0.36828877,  0.37715847, -0.28972396,  1.02121961, -0.18266918])

In [51]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, num=10)


array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.
